"""
Django settings for fdms_project project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-jwuu_kt!k61sm@gv(nxf#^+wf%2@l16mi$)83k!7_u%z^@*dna"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["www.resumeweaver.co.zw", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "rest_framework",
    "rest_framework_simplejwt",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "dashboard",
    "device_identity",
    "fiscal",
    "invoices",
    "offline",
    "legal",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "fdms_project.jwt_middleware.JWTAuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fdms_project.urls"
LOGIN_URL = "/admin/login/"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "dashboard.context_processors.dashboard_nav",
                "fiscal.context_processors.fdms_device",
            ],
        },
    },
]

WSGI_APPLICATION = "fdms_project.wsgi.application"
ASGI_APPLICATION = "fdms_project.asgi.application"

# Celery
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/1")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/2")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_ALWAYS_EAGER = os.environ.get("CELERY_TASK_ALWAYS_EAGER", "false").lower() == "true"

# Channels (WebSocket) - use InMemoryChannelLayer when Redis not configured
_REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [_REDIS_URL]},
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# JWT (REST Framework + Simple JWT)
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# FDMS Integration Settings (use env in production)
FDMS_ENV = os.environ.get("FDMS_ENV", "TEST")
_FDMS_BASE_URL = os.environ.get("FDMS_BASE_URL")
if _FDMS_BASE_URL:
    FDMS_BASE_URL = _FDMS_BASE_URL
else:
    FDMS_BASE_URL = "https://fdmsapitest.zimra.co.zw"  # Test default

if DEBUG and FDMS_ENV == "PROD":
    import warnings
    warnings.warn("DEBUG=True with FDMS_ENV=PROD. Block production API in development!", UserWarning)
FDMS_DEVICE_ID = 32327
FDMS_DEVICE_SERIAL_NO = "flyquest-6"
FDMS_ACTIVATION_KEY = "00155070"
FDMS_DEVICE_MODEL_NAME = "Server"
FDMS_DEVICE_MODEL_VERSION = "v1"

# QuickBooks Integration (optional)
QB_CLIENT_ID = os.environ.get("QB_CLIENT_ID", "ABoIRVuxq2zIe8UuPVSjQ9rZgnmqKF9TWCUaLp9FT8utnvoT2Q")
QB_CLIENT_SECRET = os.environ.get("QB_CLIENT_SECRET", "oiVAlPZMdAjFe9FvQr72nDwIy1iwsEfvMLF11nB8")
QB_REDIRECT_URI = os.environ.get("QB_REDIRECT_URI", "https://www.resumeweaver.co.zw/api/integrations/quickbooks/oauth/callback/")
QB_WEBHOOK_VERIFIER = os.environ.get("QB_WEBHOOK_VERIFIER", "")
QB_REALM_ID = os.environ.get("QB_REALM_ID", "")
QB_ACCESS_TOKEN = os.environ.get("QB_ACCESS_TOKEN", "")

# ZIMRA Section 11 QR verification URL for invoice deep link
ZIMRA_QR_URL = "https://invoice.zimra.co.zw"

# Logging Configuration
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
        "json": {
            "()": "fiscal.logging_formatter.JSONFormatter",
            "datefmt": "%Y-%m-%dT%H:%M:%S",
        },
    },
    "handlers": {
        "fdms_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "fdms.log",
            "formatter": "simple",
        },
        "fdms_json_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "fdms_json.log",
            "formatter": "json",
        },
        "fdms_error_file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "fdms_error.log",
            "formatter": "simple",
        },
        "fdms_error_json_file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "fdms_error_json.log",
            "formatter": "json",
        },
    },
    "loggers": {
        "fiscal": {
            "handlers": ["fdms_file", "fdms_json_file", "fdms_error_file", "fdms_error_json_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
